### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [nvimtools/hydra.nvim#28]
Hi, I love and use this plug-in every day for git and DAP debugging! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by miversen33** [comment]
That's an interesting concern. @benlubas @Frederick888 thoughts?

I'm completely fine with adding some sort of OSS license, but I am unsure which one would be preferred.

Typically I use MIT simply because I'm not usually doing anything life changing or ground breaking lol and I wouldn't consider hydra any of those things either. I don't believe the original version we're forked from has a license either so technically hydra is unlicensed.

**Comment by benlubas** [comment]
Oh wow. I kinda just assumed the plugin we forked had an oss licence lol. 

MIT sounds good to me

**Comment by miversen33** [comment]
I have set the License for this project to MIT, though do understand that if the overarching org (nvimtools) decides it should be something else, we may have to reconsider. I don't foresee that happening but did want to call it out.

**Comment by Frederick888** [comment]
MIT sounds good to me too :)

(And I didn't realise there was no licence when I contributed to the original repo either lol)
